name: GCD Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run gcd_test.sh
      run: |
        chmod +x gcd_test.sh
        ./gcd_test.sh
